# Generated by Django 3.1.7 on 2021-03-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_list',
        ),
    ]
