# Generated by Django 3.1.7 on 2021-03-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210321_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_list',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
