# Generated by Django 3.1.7 on 2021-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210323_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='templates/product_photo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_list',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_list',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
