# Generated by Django 3.1.7 on 2021-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210330_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphotos',
            name='descriprion',
        ),
        migrations.RemoveField(
            model_name='productphotos',
            name='title',
        ),
    ]
